version: "3"
services:
  node-app:
    container_name: my-express-node-app
    build: .
    volumes:
      - "C:\\Users\\DELL\\Desktop\\New folder\\src:/app/src:ro"
    ports:
      - "4000:4000"
    environment: 
      - NODE_ENV=production    
    env_file:
      - ./.env
    command: npm run start-dev